### ISSUE TITLE
How to serialize an object with a set as attribute???

### ISSUE THREAD

**Issue by frapik99** [agronholm/cbor2#10]
Hi all,
let's supposed I have the following class:

```
class Point(object):
    def __init__(self, x, y):
        self.x = x
        self.y = y
        self.set = set()
```

I need to serialize and deserialize it. I think the best approach would be to create a new encoder like the following:

```
@shareable_encoder  
    def default_encoder(encoder, value):
       print value
       serialized_state = encoder.encode_to_bytes(value.__dict__)
       encoder.encode(CBORTag(3000, serialized_state))
```

The problem is that a ```set``` object does not have ```__dict__``` how should I approach in this case?

Thanks

**Comment by agronholm** [comment]
It's taken me a while to get to this, sorry. So, why not just serialize it as a list and use a similar decoder on the other end to put a set back together?

**Comment by agronholm** [comment]
If you really want a set, I suggest you subscribe to issue #14. I'm going to close this now.
