### ISSUE TITLE
SystemError raised decoding under-long bytes

### ISSUE THREAD

**Issue by chrysn** [agronholm/cbor2#105]
When loading this byte string that came up in an EDHOC plug test, I get a SystemError:

```
>>> cbor2.loads(b'\xc7\x887\x00\x16\xb8\x96[\xdb t\xbf\xf8.Z \xe0\x9b\xec!\xf8@n\x86D+\x87\xec?\xf2E\xb7\nGbM\xc9\xcd\xc6\x82K*LR\xe9^\xc9\xd6\xb0SKq\xc2\xb4\x9eK\xf9\x03\x15\x00\xce\xe6\x86\x99y\xc2\x97\xbbZ\x8b8\x1e\x98\xdbqA\x08A^\\P\xdbx\x97L\'\x15y\xb0\x163\xa3\xefbq\xbe\\"^\xb2')
SystemError: <built-in function loads> returned NULL without setting an error
```

This happens both with the cbor2 shipped with Debian (5.2.0-4) as well with the current master 818ba624df535ac7cd300aaa6fb963a83b3656e0 (tested for `_cbor2.__file__` to be in the virtualenv I installed it in).

**Comment by chrysn** [comment]
Maybe to clarify a bit: This came up because a library was using cbor2 for heuristics on whether something looks liike it is CBOR or not. That's probably a bad thing to do (especially here where the data is not supposed to be CBOR), but then again shouldn't raise this kind of exception either.

**Comment by Sekenre** [comment]
When tested with the python impementation this gives an `OverflowError` exception. We need a way to check if a decoded integer can be used as a length (PY_SSIZE_T_MAX)

**Comment by chrysn** [comment]
Thank you!
