### ISSUE TITLE
There is no way to avoid using C backend if it's available

### ISSUE THREAD

**Issue by vizzerdrix** [agronholm/cbor2#107]
I would like to force Python backend but __init__ always uses C backend if it's possible, there is no way to disable it... or maybe I don't know something. It would be very nice if it would be possible to set it implicitly. 

```
try:
    from _cbor2 import *  # noqa
except ImportError: # <<<<<< I want it even if _cbor2 may be imported
    # Couldn't import the optimized C version; ignore the failure and leave the
    # pure Python implementations in place.
    pass
else:
    ....
```

**Comment by agronholm** [comment]
Is there prior art for this in other libraries?

**Comment by Sekenre** [comment]
In your build environment,
```shell
export CBOR2_BUILD_C_EXTENSION=0
pip install --no-binary cbor2
```

Let me know if that works for you

**Comment by Sekenre** [comment]
If you want to use the pure python version while still having the C lib installed (e.g. for performance comparisons) you can import it like this:

```python
from cbor2.encoder import dumps
from cbor2.decoder import loads
from cbor2.types import CBORTag # If you want to create your own tags
```
