### ISSUE TITLE
Python2 vs Python3 - different output from the same data

### ISSUE THREAD

**Issue by vizzerdrix** [agronholm/cbor2#108]
I try to port my code from Py2 to Py3 and I've met a strange problem with array and dict serialization. Data encoded by Py2 and Py3 are different what causes problems with decoding them on the target devices - Py2 output code works correctly, whilst the one generated by Py3 cannot be correctly decoded. 

I use pure python implementation of cbor2 (I don't use C version)

Simple sample:
```
from lib.cbor2 import cbor2
from collections import OrderedDict
import sys

unencSku = OrderedDict()
unencSku[ -9] = [0, 'm', 'N']
unencSku[  0] = {1: 2, '3': '4'}

inputAad = cbor2.dumps(unencSku, canonical=True)
file = open('cbort_test_verify'+str(sys.version_info.major)+"_"+str(sys.version_info.minor)+".txt", 'wb')
file.write(inputAad)
file.close()
```

I would expect two exact files, but there are different, I didn't investigate what's wrong.

**Comment by agronholm** [comment]
On Python 2, you are encoding bytes while on Python 3 you are encoding unicode strings. Try adding `from __future__ import unicode_literals` to the top and see the outputs are still different.
