### ISSUE TITLE
Provide binary wheels

### ISSUE THREAD

**Issue by letmaik** [agronholm/cbor2#109]
By default, the C extension will be built from source. This will fail on Windows if no suitable compiler is available (EDIT: it won't, since the extension is marked as optional, which ignores failures). Similar to numpy and other packages that rely on native code it would be good to publish binary wheels for all supported platforms to avoid the requirement for client-side compilation.

**Comment by agronholm** [comment]
There is already a workflow for automating the building of binary wheels on all three major platforms, but looking at the latest run of that workflow, something seems to have gone wrong. The logs are no longer available but running it again should provide some insight. I will look into this if @Sekenre is too busy.

**Comment by agronholm** [comment]
It seems that there was no valid PyPI token present for the project. I have added such a token now and tested wheel upload on testpypi: https://test.pypi.org/project/cbor2/0.0.post1/#files

@Sekenre Releasing new wheels would require a patch version bump. Are you available for that in the next couple days?

**Comment by Sekenre** [comment]
@agronholm i should have time this weekend

**Comment by agronholm** [comment]
@Sekenre It doesn't look like anything happened over the weekend. If you're too busy, let me know and I will make a new patch release.

**Comment by Sekenre** [comment]
@agronholm Please do, Thanks! Family commitments took me away from the computer :)

**Comment by agronholm** [comment]
Released v5.3.0 along with binary wheels.
