### ISSUE TITLE
Truncated byte string inside Tag 24 does not raise exception

### ISSUE THREAD

**Issue by becarpenter** [agronholm/cbor2#11]
It's a bit sad but I just reported this issue for the original Python cbor and I find it also applies to cbor2:

If cbor2.loads() encounters a Tag 24 (CBOR-in-CBOR) item whose byte string is accidentally truncated, it does not throw an exception; it simply returns a truncated result. Here's an example. The call 'cbor2.loads(raw2)' should raise an exception, because the Tag 24 length indicates 233 (0xe9) bytes but there are fewer than that. (Carsten Bormann confirms that the Ruby code does raise EOFError in this case.)

Tested on Windows/Python 3.

import cbor2
raw1=bytes.fromhex('d81858e95900e686782650545220202a205a65726f636f6e662e5f687474702e5f7463702e646e732d73642e6f72672e82781853525620302030203830207a65726f636f6e662e6f72672e70412035302e3139372e3133382e31303178185458542022747874766572733d31222022706174683d2f22782b50545220202a204d756c74696361737420444e532e5f687474702e5f7463702e646e732d73642e6f72672e82781c53525620302030203830206d756c746963617374646e732e6f72672e70412035302e3139372e3133382e31303178185458542022747874766572733d31222022706174683d2f22')
print(cbor2.loads(raw1))
##outputs: CBORTag(24, b'Y\x00\xe6\x86x&PTR  * Zeroconf._http._tcp.dns-sd.org.\x82x\x18SRV 0 0 80 zeroconf.org.pA 50.197.138.101x\x18TXT "txtvers=1" "path=/"x+PTR  * Multicast DNS._http._tcp.dns-sd.org.\x82x\x1cSRV 0 0 80 multicastdns.org.pA 50.197.138.101x\x18TXT "txtvers=1" "path=/"')
raw2=bytes.fromhex('d81858e95900e686782650545220202a205a65726f636f6e662e5f687474702e5f7463702e646e732d73642e6f72672e82781853525620302030203830207a65726f636f6e662e6f72672e70412035302e3139372e3133382e31303178185458542022747874766572733d31222022706174683d2f22782b50545220202a204d756c74696361737420444e532e5f687474702e5f7463702e646e732d73642e6f72672e82781c53525620302030203830206d756c746963617374646e732e6f72672e70412035302e3139372e3133382e31303178185458542022747874766572733d312220')
print(cbor2.loads(raw2))
##outputs:  CBORTag(24, b'Y\x00\xe6\x86x&PTR  * Zeroconf._http._tcp.dns-sd.org.\x82x\x18SRV 0 0 80 zeroconf.org.pA 50.197.138.101x\x18TXT "txtvers=1" "path=/"x+PTR  * Multicast DNS._http._tcp.dns-sd.org.\x82x\x1cSRV 0 0 80 multicastdns.org.pA 50.197.138.101x\x18TXT "txtvers=1" ')
print(len(raw1),len(raw2),0xe9)
##outputs:  237, 229, 233

**Comment by becarpenter** [comment]
If you prefer Python 2 here you go. I also checked that it fails on Linux:
import cbor2
import binascii
raw1=binascii.a2b_hex('d81858e95900e686782650545220202a205a65726f636f6e662e5f687474702e5f7463702e646e732d73642e6f72672e82781853525620302030203830207a65726f636f6e662e6f72672e70412035302e3139372e3133382e31303178185458542022747874766572733d31222022706174683d2f22782b50545220202a204d756c74696361737420444e532e5f687474702e5f7463702e646e732d73642e6f72672e82781c53525620302030203830206d756c746963617374646e732e6f72672e70412035302e3139372e3133382e31303178185458542022747874766572733d31222022706174683d2f22')
print cbor2.loads(raw1)
##outputs: CBORTag(24, b'Y\x00\xe6\x86x&PTR  * Zeroconf._http._tcp.dns-sd.org.\x82x\x18SRV 0 0 80 zeroconf.org.pA 50.197.138.101x\x18TXT "txtvers=1" "path=/"x+PTR  * Multicast DNS._http._tcp.dns-sd.org.\x82x\x1cSRV 0 0 80 multicastdns.org.pA 50.197.138.101x\x18TXT "txtvers=1" "path=/"')
raw2=binascii.a2b_hex('d81858e95900e686782650545220202a205a65726f636f6e662e5f687474702e5f7463702e646e732d73642e6f72672e82781853525620302030203830207a65726f636f6e662e6f72672e70412035302e3139372e3133382e31303178185458542022747874766572733d31222022706174683d2f22782b50545220202a204d756c74696361737420444e532e5f687474702e5f7463702e646e732d73642e6f72672e82781c53525620302030203830206d756c746963617374646e732e6f72672e70412035302e3139372e3133382e31303178185458542022747874766572733d312220')
print cbor2.loads(raw2)
##outputs:  CBORTag(24, b'Y\x00\xe6\x86x&PTR  * Zeroconf._http._tcp.dns-sd.org.\x82x\x18SRV 0 0 80 zeroconf.org.pA 50.197.138.101x\x18TXT "txtvers=1" "path=/"x+PTR  * Multicast DNS._http._tcp.dns-sd.org.\x82x\x1cSRV 0 0 80 multicastdns.org.pA 50.197.138.101x\x18TXT "txtvers=1" ')
print len(raw1),len(raw2),0xe9
##outputs:  237, 229, 233

**Comment by agronholm** [comment]
For the record, this had nothing to do with tags in particular.

**Comment by agronholm** [comment]
I've released v4.0.1 which addresses this.
