### ISSUE TITLE
Question of how to use the library or how to decode cbor payload

### ISSUE THREAD

**Issue by alexnanzer** [agronholm/cbor2#110]
Hi. 

This format is completely new to me, thats why I ask and open this issue. Maybe someone can help me. 

I have this:
8583011866018201FA41B666668202FA41FCCCCD820319020A820400

And should decode this into some values. 
I have the following but not much more.

**Packet Layout**
The design of the packet layout evolved around the needs to uniquely identify the device and sensors (one or more) being connected to a specific device.

The general packet layout consists of two parts
- The packet header
- Zero or more measurement tuples

The components of a data packet are designed as an Array of Arrays in CBOR encoding. That said, a pseudo packet definition looks like the following JSON-alike CBOR diagnostic definition.

```
[
   [
      257,
      // Vendor Id (hex 0x0101) 273,
      // Device Id (hex 0x0111)
1 // Port Id
   ],
   [
      1,
      // Transfer Id
123 // Measurement Value
   ],
   
]
```

**Measurement Tuples**
Measurements carried in the data packet are encoded into tuples of Transfer Id and the actual value.

Someone an idea? Thanks in advance.

**Comment by agronholm** [comment]
This sounds like it belongs to StackOverflow, not here. Or you having difficulties decoding a CBOR bytestring with this library?

**Comment by alexnanzer** [comment]
thanks @agronholm I will open an issue in stackoverflow aswell

**Comment by agronholm** [comment]
I will close this one then. If you have an actual bug to report, please open a new ticket.

**Comment by alexnanzer** [comment]
Now I am a step further and I am sure you can help me with ease as an expert.

How can I make 
`[[1, 102, 1], [1, 22.799999237060547], [2, 31.600000381469727], [3, 522], [4, 0]]`

from
`8583011866018201FA41B666668202FA41FCCCCD820319020A820400`

using cbor2 library?

**Comment by agronholm** [comment]
```python3
import cbor2

result = cbor2.loads(bytes.fromhex('8583011866018201FA41B666668202FA41FCCCCD820319020A820400'))
print(result)
```
But seriously, this is not the correct forum for asking for programming assistance. That's what StackOverflow is.

**Comment by alexnanzer** [comment]
Sorry but Thanks anyway.... Hopefully it helps other people too.

**Comment by nooobcoder** [comment]
Just in case if anyone wants to convert JSON to CBOR bytes, here is an example code.

```python
# A sample json dictionary
dic = {"name": "John", "age": 30, "city": "New York"}

data = cbor2.dumps(dic)

print(data.hex())
```
