### ISSUE TITLE
CBORTag() segfault

### ISSUE THREAD

**Issue by becarpenter** [agronholm/cbor2#122]
On Linux,
~~~~
import cbor2
tag = cbor2.CBORTag(54)
print(tag)
~~~~
gets a segmentation fault (backtrace available on request). I realise (after debugging) that I should do CBORTag(54, None), and the segfault does *not* happen if I do:
~~~~
import cbor2
tag = cbor2.CBORTag(54, None)
tag = cbor2.CBORTag(54)
print(tag)
~~~~
BTW, there is no problem on WIndows. 
FWIW:
cbor2 5.4.1
python 3.8.10
Linux Mint 20.2
Kernel 5.4.0-88-generic
Architecture x86-64
(but I can also create the issue on a Raspberry PI)
FYI, tag 54 is defined by draft-ietf-cbor-network-addresses.

**Comment by Sekenre** [comment]
Fixed in release 5.4.2
