### ISSUE TITLE
Implementing Typed Arrays

### ISSUE THREAD

**Issue by MarcoEsposito890** [agronholm/cbor2#128]
Is it possible to implement Typed Arrays using cbor2? And if not, will support be added in the future?

I'm transmitting a stream of fixed lenght int values and I would like to use Typed Arrays to code the lenght and type information with a single tag. According to this rec https://datatracker.ietf.org/doc/html/rfc8746 it should be doable in cbor, I was wondering if cbor2 supported it.

**Comment by Sekenre** [comment]
If you want to just use a single tag with the current version of cbor2, you can do the following:

```python
import array
import cbor2

def int_array_hook(decoder, tag, **kwargs):
    if tag.tag == 64:
        return array.array('B', tag.value)

myval = array.array('B', range(256))
encoded = cbor2.dumps(cbor2.CBORTag(64, myval.tobytes()))
assert myval == cbor2.loads(encoded, tag_hook=int_array_hook)

**Comment by MarcoEsposito890** [comment]
Hi  @Sekenre 

Thank you very much! I will try your solution.
