### ISSUE TITLE
CBOR diagnostic notation

### ISSUE THREAD

**Issue by chrysn** [agronholm/cbor2#129]
Are there plans and/or ideas on whether CBOR diagnostic notation could be supported in this package?

Currently, the only implementation I know is the ruby one the cbor-diag -- but that is rather hard to use from a Python library.

Features some of which might be considered are:

* Producing diagnostic notation
* Parsing diagnostic notation
* Hooks for diagnostic notation extension ([early draft status](https://datatracker.ietf.org/doc/draft-bormann-cbor-edn-literals/))
* Parsing and producing (possibly round-tripping) comments and indentation

API-wise it could do things like:

```python
>>> print(cbor2.dumps_diagnostic(cbor2.loads(b'\x83\x01\x02B\x01\x02')))
[1, 2, h'0102']
>>> print(cbor.dumps_diagnostic(cbor2.CBORTag(1001, {1: 1234567890})))
1001({1: 1234567890})
>>> cbor2.loads_diagnostic("[1 / a number with a comment /, <<1, 2>> / RFC8610 extensions /]")
[1, b"\x01\x02"]
```

If this is a direction that is not planned for this package but better left to a different one (that'd depend on this one), that's fine too, I'd just appreciate a statement on directons on this package.

**Comment by Sekenre** [comment]
Hi @chrysn,

Not in the near term. The focus for CBOR encoding for me is Python native data structures. CBOR decoding could potentially emit diagnostic notation particularly with the [prototype version 6](https://github.com/Sekenre/cbor2/tree/version-6) that allows tag handling to be completely customized. The place to do that would be `cbor2/tool.py` I would welcome patches for this one.

I have been playing with a [prototype token-based cbor encoder/decoder](https://github.com/Sekenre/aio-cbor) which could have a diagnostic parser added to it.

**Comment by chrysn** [comment]
If this ever gets added, I'd like to place one more potential feature on the wish list: range mapping between serialized and diagnostic CBOR. This would be practical both in interactive applications (like a dual-pane view between hex and diagnostic encoding, where the cursor position is highlighted on the other side), and for debugging (for implementing [pd-body-error-position](https://www.ietf.org/archive/id/draft-amsuess-core-pd-body-error-position-00.html#name-usage-example)).

(I'm by now not convinced any more that this package would be the best place to implement diagnostic notation, as the conversion diagnostic <-> serialized and serialized <-> objects can be pretty independent -- if any other package implements this, I'll be happy to have this closed with a reference there).

**Comment by chrysn** [comment]
Turns out, the cbor-diag crate *was* as straightforward to port as I hoped.

```python
In [1]: from cbor_diag import *

In [2]: diag2cbor("/hello!/ { 1_0: 'foo'}").hex()
Out[2]: 'a1180143666f6f'

In [3]: import cbor2

In [4]: cbor2.loads(diag2cbor("/hello!/ { 1_0: 'foo'}"))
Out[4]: {1: b'foo'}
```

There might be applications for which some tighter integration between diagnostic conversion and decoding might be desirable, but for most intents and purposes, I think this is enough. The [cbor_diag Python module in its documentation](https://cbor-diag.readthedocs.io/en/latest/) recommends cbor2 for decoding and processing.
