### ISSUE TITLE
Encode 16bit floating point

### ISSUE THREAD

**Issue by loco-philippe** [agronholm/cbor2#134]
I don't understand how to encode a value with 16bit floating point format (i try with option : canonical=True but the result is the same as  canonical=False).

Do you have some documentation or examples about this ?

Thank you

**Comment by Sekenre** [comment]
Hi @loco-philippe, The only way to make cbor2 write values in 16bit floating point format is to round the number first. Canonical mode only shortens the float if it can do so without losing precision.

What's your use case?

**Comment by loco-philippe** [comment]
Thank-you @Sekenre for your fast response. 

You're right ! If i try to encode 8.5, i get a two bytes value as expected.

My use case is  to build a standard to exchange "observation data" (ISO 19156) with Json format (https://github.com/loco-philippe/Environnemental-Sensing/blob/main/documentation/ObsJSON%20-%20Standard.pdf). A variation of this standard is to have a minimal binary version for the sensors (payload) and CBOR is really suitable for this.

So, i have to round the number first as you say. 

Is it the same situation for 32 bit floating point format ?

**Comment by Sekenre** [comment]
Yes it's the same for 32bit floating point. If you want to specify precision in a way that's more robust (ie. all values use the same precision and you don't get values exploding to 64 bits) then [rfc8746](https://www.rfc-editor.org/rfc/rfc8746.html) is what you need. I have some [work in progress code for the next major release of cbor2](https://github.com/Sekenre/cbor2/blob/version-6/cbor2/extra/arrays.py) which supports tagged arrays using Numpy.

You can also use tag hooks in the current version of cbor2 to write these arrays:

```
import struct
import cbor2

def f16_array_hook(decoder, tag, **kwargs):
    if tag.tag == 84:
        count = len(tag.value) // 2
        return list(struct.unpack(f'<{count}e', tag.value))

values = [8.5, 42.0]
encoded = cbor2.dumps(cbor2.CBORTag(84, struct.pack(f'<{len(values)}e', *values)))
assert values == cbor2.loads(encoded, tag_hook=f16_array_hook)
```

**Comment by loco-philippe** [comment]
Yes, tag 84 is a good option for binary 16 typed array.

If there is a little space left in the next release, i propose to add this "round" function.

    def round_half_precision(x):
    
        if x == 0: return 0
        sig = (x >= 0) * 2 - 1
        exp = min(max(round(math.log(abs(x), 2)), -14), 15)
        man = min(max(round(((abs(x) * 2**-exp) - 1) * 2**10), 0), 2**10)
        return sig * 2**(exp - 10) * (2**10 + man)

**Comment by Sekenre** [comment]
It may be simpler and faster to round like this `struct.unpack('<e', struct.pack('<e', value))[0]`, I could also add an option to the encoder to enforce a maximum float size.

```python
import cbor2

encoded = cbor2.dumps(23.2, max_float_size='f16')
assert cbor2.loads(encoded) == 23.203125
```

**Comment by loco-philippe** [comment]
Shame on me !!!   I should have thought of it !!!

The option is a good answer to the question, thank you.
