### ISSUE TITLE
Static type checking, and possibly automatic generation of C code

### ISSUE THREAD

**Issue by Changaco** [agronholm/cbor2#138]
cbor2 lacks [type hints](https://docs.python.org/3/library/typing.html). In addition to enabling static type checking, these annotations might allow [mypyc](https://github.com/mypyc/mypyc) to automatically generate the C version of the module. (Back in #47, using [Cython](https://github.com/cython/cython) was considered for this but ultimately rejected due to performance concerns. Perhaps mypyc can do better.)

**Comment by Sekenre** [comment]
Type hints are hopefully coming soon, I would also accept patches.
