### ISSUE TITLE
Add tag 258 for sets

### ISSUE THREAD

**Issue by Sekenre** [agronholm/cbor2#14]
An optional tag type allows for python set() objects to be encoded and decoded.

[Spec document:](https://github.com/input-output-hk/cbor-sets-spec/blob/master/CBOR_SETS.md)

**Comment by agronholm** [comment]
I like it, PR please :)

**Comment by Sekenre** [comment]
Interesting implementation problem: [In this discussion](https://github.com/cbor/cbor.github.io/issues/21)  it sounds like each tag type that could have a canonical representation needs to define how it should be encoded in canonical form. See @cabo's comment at the end: 

>  >  It would also be good to specify the canonical treatment of certain tagged values like sets.

> Yes… all tags would need to define their canonical representation — we didn’t open that can of worms in RFC 7049, but probably would have to for more extensive use of canonical.
>
