### ISSUE TITLE
Using hex value

### ISSUE THREAD

**Issue by CodeOn-ArK** [agronholm/cbor2#140]
Hi there!
How to encode a JSON format as following:
```
{
"val1" : p,
"val2" : h'1234abcd'
}
```

Where the field val2 is associated with a hex data. 
This doesn't seems to be a correct JSON format, however the web interface is able to convert it to the required CBOR format.
What is the correct representation of this format where I want to send a hex value

**Comment by Sekenre** [comment]
Hi there, I'm assuming by "web interface" you mean the [http://cbor.me]() website. That has it's own format known as "CBoR diagnostic notation" so it's not really json.

Since json can't encode binary values but CBOR can, you must decide how you represent it as text.

**Comment by AtigPurohit** [comment]
Hiii
When I am trying to convert the above data into CBOR, I am getting this error

"val1": p,
NameError: name 'p' is not defined

Can you help me out

**Comment by CodeOn-ArK** [comment]
It worked superb
