### ISSUE TITLE
Provide -none-any wheels

### ISSUE THREAD

**Issue by chrysn** [agronholm/cbor2#146]
For applications in which there is neither access to a compiler nor there is any widespread CPU architecture used, it would be convenient to provide -none-any wheels in addition to the provided binary wheels.

A concrete use case for this is pyodide, which runs Python code in the browser: At <https://pyodide.org/en/stable/console.html>, running `import micropip; await micropip.install('cbor2'), micropip.list()` shows that it falls back to cbor2 version 4.1.2, which was the last version that had such wheels.

One reason not to do this would be if pip preferred these to the platform specific ones; I don't think it does, but I did not try it.

An alternative for that particular use case might be to ask pyodide to provide the module within their build system, which would compile the C code to WASM ([they managed even with cryptography](https://github.com/pyodide/pyodide/issues/761)).

**Comment by Sekenre** [comment]
Good idea, I will look into it as soon as I can.

**Comment by agronholm** [comment]
Right, this ticket was closed but to really resolve it, a new release needs to be made.

**Comment by Sekenre** [comment]
Ok new release done.
