### ISSUE TITLE
test_decoder fails on 32 bit x86

### ISSUE THREAD

**Issue by bgermann** [agronholm/cbor2#152]
tests/test_decoder.py fails on 32 bit x86 with version 5.4.5:
```
_____________________________ test_nested_dict[c] ______________________________
tests/test_decoder.py:702: in test_nested_dict
    value = impl.loads(unhexlify("A1D9177082010201"))
E   MemoryError
---------- coverage: platform linux, python 3.11.0-final-0 -----------
```

**Comment by bgermann** [comment]
The test ran for 5.4.3; I did not try 5.4.4

**Comment by agronholm** [comment]
Might be worth trying on 5.4.4 due to `MemoryError` and a memory leak being fixed in 5.4.4.

**Comment by Sekenre** [comment]
Does the github actions test-runner support 32bit builds?

**Comment by agronholm** [comment]
Noap: https://github.com/actions/runner/issues/1181

**Comment by Sekenre** [comment]
Ok, I may be able to test at work.

**Comment by Sekenre** [comment]
Managed to reproduce it with a bit of docker magic.

**Comment by Sekenre** [comment]
With a bit of gdb work, I tracked it down. @bgermann could you try again with the latest master and let us know if that does not fix it.
