### ISSUE TITLE
UnicodeDecodeError raised instead of some CBORDecodeError

### ISSUE THREAD

**Issue by mrcljx** [agronholm/cbor2#156]
I would have expected a `CBORDecodeValueError` to be raised and caught by the following code:

```
try:
  cbor2.loads(b'\x61\x98')
except CBORDecodeError:
  ...
```

Is this something I can/should write a PR for?

**Comment by agronholm** [comment]
I think v5.6.0 fixed this. Let me know if you don't agree.
