### ISSUE TITLE
Trade-offs between cbor and cbor2

### ISSUE THREAD

**Issue by cheqianh** [agronholm/cbor2#158]
Hello!

I am new to cbor and recently looking into [`cbor`](https://pypi.org/project/cbor/) and `cbor2`, and having a question about what benefits `cbor2` brings that `cbor` does not have? 

I did experiment for their `dumps`/`loads` APIs for some sample data (E.g. a 64 bits integer, an alphabet string). In short, `cbor` uses less memory and usually runs faster.

My guess is that `cbor2` implement `RFC 8949` while `cbor` is still targeting `RFC 7049`? Is there any benefits `cbor2` brings that `cbor` does not have? Please feel free to correct me or point out a documentation that I've missed.

**Comment by cheqianh** [comment]
Benchmark:
```.py
import time
import cbor
import cbor2

o = 9233720363654371807

start = time.time()
for i in range(1000000):
    cbor.dumps(o)  
print(time.time() - start)
```

**Comment by agronholm** [comment]
`cbor` has not been maintained since 2016. It also segfaults on self referential structures, and does not implement any tag support. In short, it cuts corners which, I believe, is why it's faster.

**Comment by cheqianh** [comment]
Alright, thanks for the response!
