### ISSUE TITLE
Missing import: load

### ISSUE THREAD

**Issue by TravellerXi** [agronholm/cbor2#160]
Missing "import load" before using it in the document: https://github.com/agronholm/cbor2/blob/master/docs/usage.rst. 

The code is below:

`from cbor2 import dumps, loads

---deleted code--

with open('input.cbor', 'rb') as fp:
    obj = **load**(fp)
--deleted code--`

I advice changing the 'from cbor2 import dumps, loads' to 'from cbor2 import dumps, loads, load'.

You can refer to this Pull request: https://github.com/agronholm/cbor2/pull/159/files

**Comment by Sekenre** [comment]
#159 Has been merged thanks!
