### ISSUE TITLE
_DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated

### ISSUE THREAD

**Issue by jjakob** [agronholm/cbor2#168]
```
python3.11 setup.py build_ext -j 4
/usr/lib/python3.11/site-packages/setuptools/__init__.py:84: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
!!

        ********************************************************************************
        Requirements should be satisfied by a PEP 517 installer.
        If you are using pip, you can try `pip install --use-pep517`.
        ********************************************************************************

!!
```
Installing from Gentoo ebuild https://gitweb.gentoo.org/repo/gentoo.git/tree/dev-python/cbor2/cbor2-5.4.6.ebuild

**Comment by agronholm** [comment]
Why are you reporting this here? You're not supposed to run `setup.py` directly.

**Comment by jjakob** [comment]
If it's an issue with Gentoo packaging you can close it.

**Comment by agronholm** [comment]
We don't do packaging for Gentoo or any other OS distribution. But if you find a problem with the packaging configuration of this project, feel free to open a new issue.
