### ISSUE TITLE
Receiving CBORDecodeEOF when trying to read from tcp socket

### ISSUE THREAD

**Issue by JamieDriver** [agronholm/cbor2#177]
Hi, I am trying to migrate from using package `cbor` to `cbor2`, since this project seems actively maintained and advertises better support for more recent python versions.

The issue I have is that I am receiving:
`_cbor2.CBORDecodeEOF: premature end of stream (expected to read 1024 bytes, got 32 instead)` when trying to read from a tcp socket using the `load()` function, using a simple wrapper to provide the file-like read() function over the underlying socket.

I do not hit this issue reading from unix named pipes/fifos, or from `pyserial` serial connections, so appears to be specific to `socket` (or I need a more sophisticated wrapper?)

See below a simple example program, where the reader tries to use `load()` while the writer is sending the bytes artificially slowly.  This results in the reader getting the `CBORDecodeEOF` error.
```
#!/bin/env python

import os
import socket
#import cbor
import cbor2 as cbor
import time

payload = "my_payload_data." * 64  # 1k payload
msg = { "id": "1234", "method": "test", "payload": payload }
msg_bytes = cbor.dumps(msg)
msg_len = len(msg_bytes)
print('Encoded message length:', msg_len)

socket_endpoint = ('localhost', 37154)

class S:
  def __init__(self, endpoint, timeout):
    self.tcp_sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    self.tcp_sock.settimeout(timeout)
    self.endpoint = endpoint

  def bind_listen_accept(self):
    self.tcp_sock.bind(self.endpoint)
    self.tcp_sock.listen()
    return self.tcp_sock.accept()[0]

  def connect(self):
    self.tcp_sock.connect(self.endpoint)

  def disconnect(self):
    self.tcp_sock.close()
    self.tcp_sock = None

  # Read like a file (ie. pass to cbor.load())
  def read(self, n):
    return self.tcp_sock.recv(n)

child_pid = os.fork()

if child_pid > 0:
  # Parent process (provided with child pid)
  # Try to read message object sent by child
  time.sleep(1)

  s = S(socket_endpoint, 120)
  s.connect()
  recv = cbor.load(s)
  s.disconnect()

  assert recv == msg
  print()
  print('Message Received')

else:

  # Child process (no pid provided)
  # Write message bytes slowly
  s = S(socket_endpoint, 120)
  peer = s.bind_listen_accept()

  written = 0
  while written < msg_len:
    print('.', end='', flush=True)
    towrite = min(64, msg_len - written)
    peer.send(msg_bytes[written : written + towrite])
    written += towrite
    time.sleep(0.1)

  peer.close()
  s.disconnect()

  print()
  print('Message Sent')
```

NOTE:
* if we change the written 'chunk' size from 64b we see the number of bytes received change accordingly - ie. it looks like the receiver is interpreting a pause in bytes availability as the EOF.
* if we switch the import from `cbor2` to the older `cbor` package the problem does not occur and the cbor object is read successfully.
* if we switch the transport from `socket` to `os.mkfifo()` pipes or `pyserial` serial connections, the problem does not occur.

My project wants to read cbor objects from a variety of streams, and has no control over the rate at which the bytes are written/will arrive.

Many thanks.

**Comment by agronholm** [comment]
The problem is that `cbor2.loads()` was written with files in mind, and a file read will always return the requested number of bytes unless the end of file has been reached. TCP sockets, however, will return as many bytes there are currently in the kernel buffer (up to the requested amount). Thus, you need to modify your wrapper to ensure that it returns the requested number of bytes unless there was a disconnection.

**Comment by JamieDriver** [comment]
Sure - happy to update my wrapper code, no problem.  The general difficulty being that I don't really know the number of bytes I'm expecting all told - only the cbor parser knows that.  Are you saying that in the 'n' passed to the read() function is indeed the number of bytes expected for the next cbor object - so I can always assume that many bytes should arrive eventually ?

Odd that it seems to work with fifos even with an artificially slow writer, and with serial connection (which you'd imagine are pretty slow in a lot of cases).

**Comment by agronholm** [comment]
While I'm pretty out of touch with the code in question, I think it's a safe assumption, yes. So buffer data until either the other side disconnects or the request is fulfilled. Remember not to read too much data from the stream though.

I can only venture a guess that the other socket types block until the requested amount of data is available.

**Comment by JamieDriver** [comment]
Yes, I'm sure you're right.  My bad.  It was always bound to be, really.
```
  # Read like a file (ie. pass to cbor.load())
  def read(self, n):
    buf = self.tcp_sock.recv(n)
    while len(buf) < n:
        buf += self.tcp_sock.recv(len(buf) - n)
    return buf
```
Something like this ^ seems to work as expected.

Many thanks for the pointer.

**Comment by agronholm** [comment]
Suggestion:
```python
# Read like a file (ie. pass to cbor.load())
def read(self, n):
    buf = b""
    while n:
        if not (data := self.tcp_sock.recv(n)):
            break

        buf += data
        n -= len(data)

    return buf
```
