### ISSUE TITLE
out of memory when `cbor2.load` is given untrusted input?

### ISSUE THREAD

**Issue by dansgithubuser** [agronholm/cbor2#186]
### Things to check first

- [X] I have searched the existing issues and didn't find my bug already reported there

- [X] I have checked that my bug is still present in the latest release

### cbor2 version

5.4.6

### Python version

3.10.12

### What happened?

I am giving `cbor2.load` untrusted input in the following manner. I want to seek from the end of a file valid CBOR encodings. Along the way, I am guessing that random input is instructing CBOR to allocate a large amount of memory.

Am I right about this behavior? Would CBOR allocate a large amount of memory if told to? Note that JSON wouldn't have this problem because it's indeterminate -- it makes the claim at the bottom of the readme a bit weaker.

Some ideas that come to mind:
- a check function that doesn't allocate memory, but either gives an error like `cbor2.load` would, or outputs the memory needed
- some kind of bound to `cbor2.load`?

I think a workaround using `CBORDecoder` would be insufficient. Typical users wouldn't want this behavior while debugging their code.

Happy to look deeper if you think it's a valid issue for the project.

### How can we reproduce the bug?

I'll find a simple reproduction if necessary, but I suspect this is simple problem to communicate without it.

**Comment by dansgithubuser** [comment]
Some thoughts while figuring a workaround for myself for now.

Another way to think of this: we shouldn't need to use (much) more memory than the size of serialized data.

**Comment by agronholm** [comment]
If you can find such an issue, I'm willing to fix it but I'm not going to spend any time on a wild goose chase.

**Comment by dansgithubuser** [comment]
I am hoping for a quick pointer to where maps are decoded in the source. I found `CBORDecoder_decode_map` listed in `source/decoder.c` but couldn't find its definition.

**Comment by agronholm** [comment]
Looks like to me it starts from line 877?

**Comment by dansgithubuser** [comment]
OK thanks! I got the wrong thing to search for from `CBORDecoder_methods`. Anyway this is indeed a wild goose chase, I must have hit some other problem.
