### ISSUE TITLE
Encoder for simple values produces malformed 2-byte sequences for values between 20 and 32 because of hex<->decimal confusion

### ISSUE THREAD

**Issue by KarstenHohmeier** [agronholm/cbor2#187]
### Things to check first

- [X] I have searched the existing issues and didn't find my bug already reported there

- [X] I have checked that my bug is still present in the latest release

### cbor2 version

5.5.0

### Python version

3.9.5

### What happened?

Hello,

The standard (https://datatracker.ietf.org/doc/html/draft-ietf-cbor-7049bis-16#section-3.3) says:

> An encoder MUST NOT issue two-byte sequences that start with 0xf8 (major type 7, additional information 24) and continue with a byte less than 0x20 (32 decimal).  Such sequences are not well-formed.

But the curent code seems to confuse 20 (dec) with 0x20 (hex) 32 (dec).

https://github.com/agronholm/cbor2/blob/1e29c288e8e96272bdc4b12891d8ad0db3a86fd9/source/encoder.c#L1634-L1638

### How can we reproduce the bug?

```>>> from cbor2 import dumps, CBORSimpleValue
>>> print(dumps(CBORSimpleValue(19)))
b'\xf3'
>>> print(dumps(CBORSimpleValue(20)))
b'\xf8\x14'
>>> print(dumps(CBORSimpleValue(21)))
b'\xf8\x15'
>>> print(dumps(CBORSimpleValue(31)))
b'\xf8\x1f'
```
The encoding up to 19 is ok. 20 to 31 is malformed.

**Comment by KarstenHohmeier** [comment]
The Python code seems to have the same bug here:

https://github.com/agronholm/cbor2/blob/1e29c288e8e96272bdc4b12891d8ad0db3a86fd9/cbor2/_encoder.py#L611C1-L615C65

**Comment by agronholm** [comment]
Ok, so all I have to do to fix this is to change `20` to `0x20` (or `32`)?

**Comment by agronholm** [comment]
Hm, no, that's not quite right either. Simple values between 24 and 31 are reserved and forbidden from being output from the encoder. Thus it should raise an error if one tries to create a simple value in that range. 20 to 23 are valid but are meant for constants like `true`, `false` and `undefined`. Perhaps `CBORSimpleValue` should not accept those numbers at all?

**Comment by agronholm** [comment]
Let me know if the fix in the PR looks right.

**Comment by KarstenHohmeier** [comment]
I looked at the standard again. Seems like your new range checks match up.
![image](https://github.com/agronholm/cbor2/assets/14145252/8de946a9-1e3f-4a0c-aabe-f798778da646)
I think the standard authors did not want to break the general rules for argument value decoding. So they sneaked in the floating point types and the Break symbol under the major type 'simple value'. The argument values 28..30 are malformed for any other major type, too. This then leaves only 0..23 and 32..255 as possibly valid simple values. Thumbs up from me :)

**Comment by KarstenHohmeier** [comment]
Sorry to bother again. But did you actually fix the encoding problem for the small values, where it emits 2 bytes instead of one (the 20dec <-> 0x20hex confusion)? Maybe I overlooked it, but i did not see that in the branch you merged. Without that the encoding would still be wrong for simple value 20, 21 and 22.

**Comment by agronholm** [comment]
You're right – I changed my approach a couple times while trying to understand the issue that I actually didn't fix the original complaint! I've done that now in 48395942.
