### ISSUE TITLE
Please add pipx support

### ISSUE THREAD

**Issue by hexagonrecursion** [agronholm/cbor2#199]
### Things to check first

- [X] I have searched the existing issues and didn't find my feature already requested there

### Feature description

I would like to be able to run cbor.tool by running `pipx run cbor2`. Currently I get this:
```
pipx run cbor2
'cbor2' executable script not found in package 'cbor2'.
Available executable scripts:
```

### Use case

pipx is awesome. It creates virtual environments for each app and automatically manages them. It installs the app, if it is not already installed. It automatically installs updates. Virtual environments are great - it makes it possible to install apps that require incompatible dependency versions (also: without virtual environments the user has to manage one giant "[kitchen sink](https://en.wiktionary.org/wiki/everything_but_the_kitchen_sink)" environment, which can be hard), but virtual environments are hard to manage manually (hence pipx).

**Comment by agronholm** [comment]
Ok, so the request is to add an entry point named `cbor2` in the `console_scripts` namespace?

**Comment by hexagonrecursion** [comment]
According on [pipx documentation](https://pipx.pypa.io/stable/how-pipx-works/#developing-for-pipx) console_scripts appears to be the right place to add this.
