### ISSUE TITLE
Failing unit-test

### ISSUE THREAD

**Issue by meejah** [agronholm/cbor2#209]
### Things to check first

- [X] I have searched the existing issues and didn't find my bug already reported there

- [X] I have checked that my bug is still present in the latest release

### cbor2 version

5.6.0

### Python version

3.11.5

### What happened?

I ran `python -m pytest -sv tests/` and one of the date tests failed:

```
tests/test_decoder.py:389: in test_date
    assert decoded == expected
E   assert datetime.date(2018, 12, 30) == datetime.date(2018, 12, 31)
```

### How can we reproduce the bug?

run `python -m pytest -sv tests/test_decoder.py`

**Comment by agronholm** [comment]
I can't reproduce this, nor does this happen in the CI. I need you to dig deeper and see what's going on.

**Comment by meejah** [comment]
With Python 3.11.5, I run `python setup.py build` to get a `/build/lib.linux-x86_64-cpython-311/_cbor2.cpython-311-x86_64-linux-gnu.so` which I then move to "." so that it is picked up by python.

Then, running the above command causes the error.

This is a Debian stable derived OS (PureOS 10 / Byzantium). I also tried on a clean clone on a Debian 12 (bookworm) system (with python 3.11.2) with the same results.

**Comment by meejah** [comment]
So far, the answer is "no". I'm guessing it's "something locales? maybe?"

Here's what I have so far (this works, still fails on host system):

```
FROM debian

RUN apt update 
RUN apt install -y locales python3 python3-setuptools python3-pip python3-wheel git build-essential python3-venv && rm -rf /var/lib/apt/lists/* && localedef -i en_CA -c -f UTF-8 -A /usr/share/locale/locale.alias en_CA.UTF-8
ENV LANG en_CA.utf8
RUN cd / && git clone https://github.com/agronholm/cbor2.git
RUN env
RUN cd /cbor2 && python3 -m venv venv && ./venv/bin/pip install .[test] && python3 setup.py build && mv /cbor2/build/lib.linux-x86_64-cpython-311/_cbor2.cpython-311-x86_64-linux-gnu.so . && ./venv/bin/python3 -m pytest -sv tests/test_decoder.py
RUN locale
```

One thing I do notice when looking, though, is that the Python code for "semantic type 100" is doing `date.fromordinal(x + 719163)` whereas the corresponding C code is doing `PyDate_FromTimestamp()` and multiplying the encoded value by seconds-per-day (`24*60*60`).

So I'm not claiming either is "wrong", but they're definitely "different".

Any ideas on what might be different  from host -> docker that might explain this? (They're both now a Canadian utf8 locale ...)

**Comment by agronholm** [comment]
Ok, looking at the docs, it would seem that `date.fromtimestamp()` might indeed be affected by the locale. There is, however, no direct C API equivalent for `date.fromordinal()` – perhaps I could call that as I would call any Python function though?

**Comment by agronholm** [comment]
I guess you're on a time zone with a negative UTC offset (if in Canada), and that might affect the results?

**Comment by meejah** [comment]
yes, I'm UTC-6 or -7 normally -- but I did try my best to have the locale set to "canada, english" in the Docker container (however, I don't do much docker, so maybe that part isn't working as I intended)

**Comment by meejah** [comment]
p.s. since you're already depending on Hypothesis, it might be good to have more tests that let it explore weird cases (e.g. a "round-trip dates" test that uses `hypothesis.strategies.dates`)

This is (indirectly) how we found the other bug (with "binary strings over 65536 bytes")...

**Comment by agronholm** [comment]
Unfortunately it seems like hypothesis also considerably slows down each test it's applied on. If I were to do the same with each type supported by cbor2, I fear it might make the test suite many times slower. I could be persuaded otherwise with some benchmarks though.

**Comment by meejah** [comment]
Yes, it tries 100 "examples" for each `@given` by default I believe. You can set it to do substantially fewer (e.g. during development, to speed up test-runs). Here's one way to do that: https://github.com/tahoe-lafs/magic-folder/blob/88f6c9266fb2218fac5608911f8130aea6ce972c/src/magic_folder/test/__init__.py#L59

It's definitely a bit of a tradeoff: you get "many tests", shrinking and theoretically better coverage -- but it takes more time. To be fair, it would also take more time if you had 100 test-cases for each kind, but ...

I think the most "bang" here can be for things that you _know_ can be weird, like UTF strings. On the flip side, having a couple very-specific cases for e.g. binary strings (where the actual content is unlikely to matter in this case) might be a better answer to the trade-off.

Another way to approach the slowdown problem would be to use `@pytest.mark` to mark those tests as "slow" and only run them in CI by default (so you get some property-testing / "fuzzing"-ish tests in CI).

**Comment by agronholm** [comment]
I have a fix for this almost ready, but I'm currently on vacation so it'll have to wait until at least next Sunday.

**Comment by agronholm** [comment]
Would you mind reviewing the PR?
