### ISSUE TITLE
CBOR allows binary strings which cannot be mapped to JSON

### ISSUE THREAD

**Issue by spletinckx** [agronholm/cbor2#250]
### Things to check first

- [X] I have searched the existing issues and didn't find my bug already reported there

- [X] I have checked that my bug is still present in the latest release

### cbor2 version

5.6.5

### Python version

3.10.12

### What happened?

When creating a CBOR object, the package allows to use binary strings as values. However, this is not supported by JSON. RFC 8949 says the following:

> 6.  The format must support all JSON data types for conversion to and
       from JSON.
       *  It must support a reasonable level of conversion as long as
          the data represented is within the capabilities of JSON.  It
          must be possible to define a unidirectional mapping towards
          JSON for all types of data.

As a result, when I try to convert from CBOR to JSON, my JSON breaks on the binary value.

### How can we reproduce the bug?

```
import json
import cbor2

data = {
    "my_string": b"some string data",
}

cbor_data = cbor2.dumps(data)
print(cbor_data)

json_data = json.dumps(data)
print(json_data)
```

Which yields `b'\xa1qmy_stringX\x1bsome string data'` for the CBOR print.

and `TypeError: Object of type bytes is not JSON serializable` for the JSON print.

**Comment by agronholm** [comment]
I believe you are misinterpreting the spec. First of all, the section you quoted was from a non-normative section (CBOR design goals). It says to support all JSON types, it doesn't say anything about *also* supporting types that JSON cannot encode. [Section 6.1.1](https://datatracker.ietf.org/doc/html/rfc8949#section-6.1-1) makes this quite clear in my opinion.

Furthermore, the [mapping section](https://datatracker.ietf.org/doc/html/rfc8949#section-3.1-2.12) does not place any limitations on the types of keys or values in a CBOR mapping.

I checked the second most popular implementation (`cbor`), and that too encodes a binary value just as expected.

**Comment by spletinckx** [comment]
Thank you for the clarification! In that case, I indeed agree that binary strings can be used.
Given that, shouldn't it still lead to a conversion to JSON without raising an exception since 6.1.1 states that "A byte string (major type 2) that is not embedded in a tag that specifies a proposed encoding is encoded in base64url without padding _and becomes a JSON string._"

Don't want to be annoying, just want to clarify since I am only recently getting familiar with this RFC :)

**Comment by agronholm** [comment]
> Given that, shouldn't it still lead to a conversion to JSON

What would convert to JSON where?

**Comment by spletinckx** [comment]
The binary string becoming a JSON string.

**Comment by agronholm** [comment]
No, you're not getting what I'm asking. I'm asking what would be converting a binary string into a JSON string? I see no mechanism that should cause something like that to happen. Not that it makes any sense either – not all binary strings _can_ be converted to unicode strings anyway.
