### ISSUE TITLE
Overflow error encoding large float with canonical=True

### ISSUE THREAD

**Issue by bmerry** [agronholm/cbor2#26]
```python
>>> cbor2.dumps(1e300, canonical=True)
OverflowError: float too large to pack with f format
```

Using cbor2 4.1.1.

**Comment by Sekenre** [comment]
Fixed in master. Will do a release soon.

**Comment by agronholm** [comment]
@Sekenre Talk to me before you do a release. I want to make sure you know the proper procedure for that.

**Comment by Sekenre** [comment]
@agronholm Sure, You can message me over Linkedin and we could exchange email addresses GPG keys or whatever. Or I'll just '@' you when I'm ready to tag.
