### ISSUE TITLE
Support encoding a stream without first reading it into memory

### ISSUE THREAD

**Issue by vashek** [agronholm/cbor2#34]
Support encoding a stream without first reading it into memory. Something like:
x = cbor2.dumps({"name": open("file.zip", "rb")})

(The other part of this would be to then return a file-like object from which the caller can read the encoded stream, so that neither the input nor the output ever needs to be entirely in memory.)

**Comment by Sekenre** [comment]
Hi @vashek, what's your use case for this? It sounds like you want to encapsulate a large opaque blob of data into a CBOR object. This would mean that the reciever process would have to fit the whole thing in memory. (you can't serialize file pointers, try it with pickle!)

 If I had to do this I would write a header in CBOR and then append the blob after it like this:

```python
from cbor2 import CBOREncoder

with open('output.xyz', 'wb') as out:
    encoder = CBOREncoder(out)
    encoder.encode({'name': 'file.zip'})
    with open('file.zip', 'rb') as _in:
        reader = lambda: _in.read(1024)
        for block in iter(reader, b''):
            out.write(block)
```

A word of warning though, cbor2 is unaffected by trailing data when decoding but other decoders in other languages may complain.

I plan to add this to the documentation soon as it seems to come up a lot.

**Comment by vashek** [comment]
The use case is uploading a document into an ElasticSearch ingest node using an Ingest Attachment Processor Plugin. See https://www.elastic.co/guide/en/elasticsearch/plugins/current/ingest-attachment.html. So I have to work with an existing API. Your suggestion makes sense I suppose, but I would have to redefine the contract and modify the server side as well, which I can't.

**Comment by Sekenre** [comment]
Here's an even easier way to share the buffer between the cbor2 encoder and requests:

```python
from cbor2 import dump
from io import BytesIO
import requests

data = BytesIO()
with open('file.zip', 'rb') as f:
    dump({'name': 'file.zip', 'content': f.read() }, data)
data.seek(0) # go back to the beginning of the buffer
requests.post('http://some.url/streamed', data=data)
```

Going to close this. If you find that it works, raise a new issue or PR so we can document how you ended up doing it.

**Comment by vashek** [comment]
I don't think that what you're suggesting is significantly better that my original one-liner: in all cases, you need to have the entire file in memory, times two.

What I imagine would be a great solution is if I could say something like:
```
with open('file.zip', 'rb') as f:
    simulated_file = cbor2.dump_as_file({'name': f.name, 'content': f}
    requests.post('http://some.url/streamed', data=simulated_file)
```

The idea is that dump_as_file would return a file-like object with a read() method that only returns as much data as requested, and only reads as much data from the source file(s) as needed to generate the requested piece of the result.

But at this moment, this is just an idea for improvement. Hopefully the project I work on won't encounter files large enough that this would become a problem, and I am not currently motivated enough to work on this without a pressing need, so sure, feel free to close...

**Comment by Sekenre** [comment]
If there was another encoder in python like pickle, json, base64 or marshal, which supported a similar interface, I would have something to build a streaming API  on.

I'm quite interested in the problem but haven't seen the way to do it.
