### ISSUE TITLE
How to effiently encode a list of dicts

### ISSUE THREAD

**Issue by BrendanSimon** [agronholm/cbor2#35]
I have a program that periodically accumulates a set of data into a dictionary and queues (appends) the dictionary to a list.  When the list gets to a certain size (60), the list is converted to CSV format (using csv.DictWriter).

I want to make the transport usage more efficient and using CBOR seems like a good fit (instead of ascii text).

If I encode each dict using `dumps()`, then each key field is encoded and duplicated.  This is inefficient as there are multiple copies (60) of each key field.

Is there a way to encode this more efficiently with cbor2, where the keys are only represented once? (with csv this encoded in the first line as a header).

Does using something like Pandas or Numpy (or even sqllite3?) and cattrs.unstructure() help in any way?

**Comment by agronholm** [comment]
This might be possible using a certain CBOR extension but it is not supported by this library: http://cbor.schmorp.de/stringref
