### ISSUE TITLE
dates are encoded as datetimes

### ISSUE THREAD

**Issue by Changaco** [agronholm/cbor2#37]
https://github.com/agronholm/cbor2/blob/bf4acfd4ba08959a8b18f6c97981bae6d9bd22ca/cbor2/encoder.py#L156-L158

In my opinion the default behavior of the encoder should be to refuse to serialize an object if the decoder isn't capable of recreating it exactly. Converting to and from CBOR shouldn't be a lossy operation.

**Comment by Sekenre** [comment]
This is a limitation of CBOR not having a distinct datatype for a bare date. There is a proposed extension tag here https://j-richter.github.io/CBOR/date.html which we could use.

See the mailing list discussion here: https://mailarchive.ietf.org/arch/msg/cbor/p_T6fvA31vC4DJKWWoeLLTKd4Us

I agree it shouldn't be encoding the current time along with the date.

**Comment by agronholm** [comment]
Yet there could be people relying on this. If the logic is changed either way, it will require a major version bump.

**Comment by Sekenre** [comment]
Agreed. How do you feel about using the warnings module?

i.e. raise a deprecation warning when someone encodes a date?

**Comment by agronholm** [comment]
Using the warnings module seems like a good idea, but a deprecation warning? We're not deprecating the ability to encode dates, right?

**Comment by agronholm** [comment]
Or which way do you want to go? Remove the ability to encode dates like originally suggested here?

**Comment by Sekenre** [comment]
I've been reading the warnings module documentation and thinking about this.

There's no accepted round-trip encode/decode without custom tags. So I'm in favour of removing it unless it's being used by everyone, in which case we just raise a UserWarning.

Perhaps eventually we could have a module of datatypes that are not imported by default. like this:

```python
from datetime import date
from cbor2 import dumps, loads
from cbor2.extra import encode_date, decode_date, date_tag

encoded = dumps(date(2019, 3, 17), extra_encoders={date: encode_date})
print(loads(encoded, extra_decoders={date_tag: decode_date}))
```

This changes how you would handle extending cbor2 with new datatypes, which would also require a major version bump.

**Comment by Sekenre** [comment]
Hi @Changaco there's been a few changes that break your proposed PR. If you like, I could wait before releasing the next version to give you time to update it.

**Comment by Changaco** [comment]
@Sekenre I have rebased and completed the PR.
