### ISSUE TITLE
setup.py fails on Python 2

### ISSUE THREAD

**Issue by jayvdb** [agronholm/cbor2#38]
Very likely caused by `author = Alex Grönholm` in setup.cfg

Obviously an upstream bug, but may be solvable with higher minimums.

```py
[    9s] [147/155] keeping python2-setuptools-40.7.2-1.1
[    9s] [148/155] keeping python2-setuptools_scm-3.1.0-4.2
...
[   19s] + /usr/bin/python2 setup.py build '--executable=/usr/bin/python2 -s'
[   20s] Traceback (most recent call last):
[   20s]   File "setup.py", line 10, in <module>
[   20s]     'setuptools_scm >= 1.7.0'
[   20s]   File "/usr/lib/python2.7/site-packages/setuptools/__init__.py", line 144, in setup
[   20s]     _install_setup_requires(attrs)
[   20s]   File "/usr/lib/python2.7/site-packages/setuptools/__init__.py", line 137, in _install_setup_requires
[   20s]     dist.parse_config_files(ignore_option_errors=True)
[   20s]   File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 702, in parse_config_files
[   20s]     self._parse_config_files(filenames=filenames)
[   20s]   File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 599, in _parse_config_files
[   20s]     (parser.read_file if six.PY3 else parser.readfp)(reader)
[   20s]   File "/usr/lib64/python2.7/ConfigParser.py", line 324, in readfp
[   20s]     self._read(fp, filename)
[   20s]   File "/usr/lib64/python2.7/ConfigParser.py", line 479, in _read
[   20s]     line = fp.readline()
[   20s]   File "/usr/lib64/python2.7/encodings/ascii.py", line 26, in decode
[   21s]     return codecs.ascii_decode(input, self.errors)[0]
[   21s] UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 149: ordinal not in range(128)
[   21s] error: Bad exit status from /var/tmp/rpm-tmp.9bXmyv (%build)
```

**Comment by jayvdb** [comment]
Looks like _scm 3.2.0 doesnt include a bug fix for this https://github.com/pypa/setuptools_scm/blob/master/CHANGELOG.rst

and neither does v40.7.3 or v40.8.0 of https://github.com/pypa/setuptools/blob/master/CHANGES.rst

**Comment by agronholm** [comment]
I'm struggling to reproduce this. The description says that `setup.py` fails on Python 2, but running it on my end works just fine. It seems like you're running some kind of 3rd party tool to install it. Would you mind trying to reproduce this in a virtualenv and provide exact instructions?

**Comment by jayvdb** [comment]
You can see the failure at https://build.opensuse.org/package/show/home:jayvdb:branches:home:jayvdb:moban/python-cbor2

At https://build.opensuse.org/request/show/677284 @scarabeus_iv suggests it can be fixed by `export LANG=en_US.UTF8` before calling setup.py

**Comment by agronholm** [comment]
I was able to reproduce it by setting `LANG=C` before running `setup.py build`. This looks like a setuptools bug. Please report it in that project.

**Comment by agronholm** [comment]
The underlying issue is that `setup.cfg` should always be read as UTF-8, regardless of any `LANG` setting in the environment.

**Comment by jayvdb** [comment]
Apparently this is your responsibility.

See https://github.com/pypa/setuptools/issues/1661

I dont agree that everyone using unicode in their setup.cfg should need to declare it, but that seems to be what upstream is saying.

**Comment by agronholm** [comment]
I tested running `setup.py build` using `LANG=C` with and without the declaration and the declaration fixes the issue.
