### ISSUE TITLE
Timestamp encoding throws away microseconds

### ISSUE THREAD

**Issue by waveform80** [agronholm/cbor2#44]
I get the impression from `encode_datetime` in encoder.py (https://github.com/agronholm/cbor2/blob/master/cbor2/encoder.py#L138) that the intention for timestamp encoding is to calculate a floating-point value to encode. Unfortunately, integer division (// instead of /) is being used with the microseconds field. Given microseconds can never be >1000000 (the value it is being divided by), the result of the division will always be 0, effectively throwing the microseconds data away.

For example, under Python 3.5:

```python3
>>> import cbor2
>>> import datetime as dt
>>> ts = dt.datetime.now()
>>> cbor2.loads(cbor2.dumps(ts, datetime_as_timestamp=1, timezone=dt.timezone.utc))
datetime.datetime(2019, 4, 16, 21, 16, 9, tzinfo=datetime.timezone.utc)
>>> cbor2.loads(cbor2.dumps(ts, datetime_as_timestamp=0, timezone=dt.timezone.utc))
datetime.datetime(2019, 4, 16, 21, 16, 9, 167883, tzinfo=datetime.timezone.utc)
```

**Comment by Sekenre** [comment]
Good Catch, thanks! I will fix tomorrow.

**Comment by waveform80** [comment]
Sorry, I've been terribly lazy in not putting together a PR for this! As a matter of possible interest: the reason I ran across this is I've been bashing together a [C-based translation] of cbor2 (for reasons elaborated in the README :) and have run across a few little bugs in cbor2 during the course of the work. I'll try and bash together tickets and PRs for them in the next couple of days (but don't worry - they're all trivial fixes).

[C-based translation]: https://github.com/waveform80/cboar.git

**Comment by Sekenre** [comment]
Ok Great! Cboar looks like a nice project.

**Comment by agronholm** [comment]
If you get it to work properly and the performance benefits are substantial, we should probably merge your code into this project and make you one of the maintainers. Agreed?

**Comment by waveform80** [comment]
> If you get it to work properly and the performance benefits are substantial, we should probably merge your code into this project and make you one of the maintainers. Agreed?

That's an interesting proposal - I'll open another ticket for the discussion rather than jumble up this one with a lot of extraneous detail (in the course of writing cboar I've made a few changes that may or may not make sense for the cbor2 project).

Anyway, in the meantime I finally got of my lazy behind and bunged a quick PR together for this ticket :)

**Comment by agronholm** [comment]
One potential problem is that you've used straight C. Could the performance benefits still be achievable if Cython was used instead?
