### ISSUE TITLE
Difference between Float and Double types when writing to CBOR

### ISSUE THREAD

**Issue by abrighton** [agronholm/cbor2#50]
Is there a way to differentiate between float and double when calling cbor2.dumps()? 
I've run into the problem that all floating point values written from Python are treated as double on the receiving end (Scala code). Is there some way to hint that certain values or arrays should be float instead of double?

**Comment by agronholm** [comment]
After decoding, there is no way to differentiate. Does this answer your question?

**Comment by abrighton** [comment]
After looking into it some more, I think the problem is on the Scala side. The problem was encoding a floating point value in python to CBOR when the Scala side expected a Float, but received a Double. The receiver needs to be able to handle both in this case. So yes, you can close this. Thanks.
