### ISSUE TITLE
Mem-leak in loads()

### ISSUE THREAD

**Issue by waveform80** [agronholm/cbor2#53]
Argh, I was afraid I hadn't caught everything in the C-based implementation and so it's turned out. When testing the C-based implementation on piwheels we had it fall over a couple of times with out-of-mem errors. A bit of further testing revealed there was definitely an issue *somewhere* in the C-based implementation but I'm afraid it's taken me about a week to track down exactly where. Turns out it's a trivial ref-leak in the C-based loads() function (it leaks the byte-string it's passed). I've got a patch in the works; just trying to figure out an extension to the ref-leak testing script to catch things like this a bit more easily in future!

Anyway, sorry about that - will post the PR hopefully tomorrow.

**Comment by waveform80** [comment]
PR added: #54

**Comment by Sekenre** [comment]
I've merged your test script and verified that it does what you describe (before and after the memory leak patch).

Thanks!

**Comment by Quatrecentquatre-404** [comment]
Hi,
I know it's closed but it describes my bug. I'm trying to load a dict as encoded string using :
```python
import json
import cbor2
data = json.dumps({ "age": 10 })
x = cbor2.loads(data.encode())
```
But it raises a ``MemoryError``. I hope you may help, or tell me if I'm wrong at any point.

**Comment by Sekenre** [comment]
Hi @Quatrecentquatre-404 

There should not be any need to call `encode()` on your data. It's already a string of bytes.

**Comment by Quatrecentquatre-404** [comment]
> Hi @Quatrecentquatre-404
> 
> There should not be any need to call `encode()` on your data. It's already a string of bytes.

Nevermind. I miss used the module. I tried things but it doesn't match with my final goal. Thanks anyway for the module.

**Comment by derinwalters** [comment]
I have a similar issue, however in my case I don't necessarily know what format the incoming bytes are in. While json.loads and msgpack.unpackb quickly throw an exception, cbor2.loads goes ballistic with memory (on my machine up to 47GB when loading the contents of a 100MB UTF-8 encoded JSON file) and seg faults without providing any opportunity to catch the exception. Is there any known suggestion for handling this case?

**Comment by Ximaz** [comment]
> I have a similar issue, however in my case I don't necessarily know what format the incoming bytes are in. While json.loads and msgpack.unpackb quickly throw an exception, cbor2.loads goes ballistic with memory (on my machine up to 47GB when loading the contents of a 100MB UTF-8 encoded JSON file) and seg faults without providing any opportunity to catch the exception. Is there any known suggestion for handling this case?

Hello Derin,
I think it would be helpful to provide a minimum reproducible example so we can try that on our side and give you feedback on our thoughts.
