### ISSUE TITLE
Decoding the full contents of a cbor-encoded urllib3 HTTPResponse

### ISSUE THREAD

**Issue by urieli** [agronholm/cbor2#55]
Using cbor2 version 4.1.2 on Python 2.7.

I'm receiving a cbor-encoded [urllib3.response.HTTPResponse](https://urllib3.readthedocs.io/en/latest/reference/#urllib3.response.HTTPResponse), which implements [io.ioBase](https://docs.python.org/2.7/library/io.html#io.IOBase).

How do I use cbor2 to decode this stream? Do I use `load`, `loads` or `CBORDecoder`? Can you give an example?

**Comment by waveform80** [comment]
Although `HTTPResponse` implements `ioBase`, that's not much use to you as by the time you get hold of it, it's read to the end of the data and you can't seek backwards. Instead, just use `loads` with the `data` attribute of the response:

```python
>>> import cbor2, urllib3
>>> http = urllib3.PoolManager()
>>> r = http.request('GET', 'http://some-url-that/returns-some-cbor.data')
>>> r.status
200
>>> cbor2.loads(r.data)
[1, 2, 3]
```

**Comment by waveform80** [comment]
Oh, looks like there is a way to get it to stream just in case you're dealing with huge CBOR content, in which case you can use `load` instead:

```python
>>> import cbor2, urllib3
>>> http = urllib3.PoolManager()
>>> r = http.request('GET', 'http://some-url-that/returns-some-cbor.data',
...     preload_content=False)
>>> r.status
200
>>> cbor2.load(r)
[1, 2, 3]
```

**Comment by urieli** [comment]
Thanks, I just realised my Python client was using `requests` rather than `urllib3`.

The commands become:
```python
>>> import cbor2, requests
>>> r = requests.get('http://some-url-that/returns-some-cbor.data',stream=True)
>>> cbor2.loads(r.raw.read())
[1, 2, 3]
```

**Comment by agronholm** [comment]
Will the following work?
```python3
r = requests.get('http://some-url-that/returns-some-cbor.data',stream=True)
cbor2.load(r.raw)
```

**Comment by urieli** [comment]
Yes, even simpler! Thanks @agronholm @waveform80
