### ISSUE TITLE
cbor2 'types.py' module triggers deprecation warning

### ISSUE THREAD

**Issue by ddiminnie** [agronholm/cbor2#58]
This is not a high-priority issue (for reasons that will become apparent below), but it will need to be addressed eventually.

The types.py module includes the following import statement:

```python
from collections import Mapping
```

This import triggers the following deprecation warning under python 3.7:

```
DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
```

According to the [python 3.8.0b4 changelog](https://docs.python.org/3.8/whatsnew/changelog.html#changelog), the decision to remove the ABC aliases from the collections module has been bumped to python 3.9, so fixing this warning is not immediately necessary (as mentioned above)... but I thought you folks would like to know about the potential problem before it becomes... um... a problem.

**Comment by agronholm** [comment]
There is no such line in [types.py](https://github.com/agronholm/cbor2/blob/master/cbor2/types.py).

**Comment by ddiminnie** [comment]
The cited line appears in the 'types.py' module in cbor2 4.1.2.

Longer listing from that release:

```python
from collections import Mapping


class CBORTag(object):
    """
    Represents a CBOR semantic tag.

    :param int tag: tag number
    :param value: encapsulated value (any object)
    """

    __slots__ = 'tag', 'value'

    def __init__(self, tag, value):
        self.tag = tag
        self.value = value
# ---- snip ----
```

Perhaps this was already changed/fixed?  (In which case there's nothing to do...)

**Comment by agronholm** [comment]
It was fixed in bf4acfd4ba08959a8b18f6c97981bae6d9bd22ca. Seems like a new release has not been made since then.

**Comment by agronholm** [comment]
@Sekenre Do you have a plan for a new release?

**Comment by ddiminnie** [comment]
Sounds like this is a duplicate issue, then.

Please accept my apologies.
