### ISSUE TITLE
Canonical cbor

### ISSUE THREAD

**Issue by jkbbwr** [agronholm/cbor2#6]
Can this library support canonical encoding

The RFC has some suggestions for canonical encoding, the most important is map ordering. Can this library support the ordering for the maps 

>    o  The keys in every map must be sorted lowest value to highest.
      Sorting is performed on the bytes of the representation of the key
      data items without paying attention to the 3/5 bit splitting for
      major types.  (Note that this rule allows maps that have keys of
      different types, even though that is probably a bad practice that
      could lead to errors in some canonicalization implementations.)
      The sorting rules are:
      *  If two keys have different lengths, the shorter one sorts
         earlier;
      *  If two keys have the same length, the one with the lower value
         in (byte-wise) lexical order sorts earlier.

**Comment by agronholm** [comment]
What do you need this for? I could accept a non-invasive PR.

**Comment by jkbbwr** [comment]
I looked into doing a PR but because you have writing quite tightly bound to encoding it makes sorting the keys very tricky without duplicating code :(

I need this for hashing and ensuring content. 

Take dictionary -> CBOR -> sha256.

**Comment by agronholm** [comment]
Could you write the code in a different manner without compromising speed and flexibility?

**Comment by jkbbwr** [comment]
You could separate the writing and encoding. Means one function call overhead when actually writing bytes? Its a real shame there is no inline directive in Python

Something like 

```
def encode_string(x): 
    return x.encode("utf8")
def write_string(x, fp): 
    fp.write(length("snip")) 
    fp.write(encode_string(x))
```

**Comment by jkbbwr** [comment]
The actual implementation of sorted maps is very simple

```
sorted_keys = sorted(map.keys(), key=lambda x: (len(x), x))
for key in sorted_keys:
    # blah
```

**Comment by agronholm** [comment]
How would the code look like with canonical vs default encoding?

**Comment by jkbbwr** [comment]
The encode method becomes

```
    @shareable_encoder
    def encode_map(self, map, fp):
        fp.write(encode_length(0xa0, len(map)))

        if self.canonical:
            keys = sorted(map.keys(), key=lambda x: (len(x), x))
        else:
            keys = map.keys()

        for key in keys:
            self.encode(key, fp)
            self.encode(map[key], fp)
```

**Comment by jkbbwr** [comment]
This might be a nice solution

```
from functools import singledispatch

import struct


@singledispatch
def encode(x, **kwargs):
    raise TypeError("I don't understand %r" % x)


@encode.register(type(None))
def encode_none(x, **kwargs):
    yield b'\xf6'


@encode.register(bytes)
def encode_bytes(x, **kwargs):
    yield x


@encode.register(bool)
def encode_bool(x, **kwargs):
    yield b'\xf5' if x else b'\xf4'


@encode.register(str)
def encode_string(x, **kwargs):
    yield x.encode("utf8")


@encode.register(list)
def encode_list(x, **kwargs):
    for i in x:
        yield from encode(i)


@encode.register(dict)
def encode_dict(x, **kwargs):
    canonical = kwargs.get("canonical", False)

    if canonical:
        # Encode the keys to bytes, order them by byte order, then get the original keys back in that order.
        order = sorted(((next(encode(key)), key) for key in x.keys()), key=lambda k: (len(k[0]), k[0]))
        keys = (key[1] for key in order)
    else:
        keys = x.keys()

    for key in keys:
        yield from encode(key)
        yield from encode(x[key])


@encode.register(int)
def encode_pos_int(x, **kwargs):
    yield struct.pack('>B', 0 | x)
```

**Comment by agronholm** [comment]
Generators were my initial approach, but performance was so atrocious that I had to abandon the idea.

**Comment by jkbbwr** [comment]
Christ the performance is horrifying.

```
In [13]: %timeit c.encode(data, BytesIO())
The slowest run took 19.35 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 1.91 µs per loop

In [14]: %timeit BytesIO().writelines(encode(data))
1000 loops, best of 3: 488 µs per loop
```

**Comment by agronholm** [comment]
What here is `c.encode`? Is `encode` the function defined above?

**Comment by jkbbwr** [comment]
`c.encode` is your encode function. `encode` is my generator one. haha

**Comment by agronholm** [comment]
Yep...otherwise the generators would've been a really elegant solution.
