### ISSUE TITLE
Docs/Clarification

### ISSUE THREAD

**Issue by felipeochoa** [agronholm/cbor2#62]
The `CBOREncoder` docstring says that setting `value_sharing` to `True`, "allows more efficient serializing of repeated values".

The main docs only reference this param in terms of cyclic structures, so I was wondering if there was a benefit to allowing this on non-cyclic but repetitive structures. Something like:

```python
a = <something large but without cycles>
cbor2.dumps({'a': a, 'x': a}, value_sharing=True)
```

**Comment by Sekenre** [comment]
Yes. If you have large objects as values in dicts or lists, and they are referenced multiple times as in your example, they will be encoded as a shared value with a back-reference.

**Comment by Sekenre** [comment]
Here's an example I made up:

```python
>>> big = dict(zip('abcdef', 'ghijkl'))
>>> big
{'a': 'g', 'b': 'h', 'c': 'i', 'd': 'j', 'e': 'k', 'f': 'l'}
>>> bigl = [ big for _ in range(200) ]
>>> len(bigl)
200
>>> bigl[:2]
[{'a': 'g', 'b': 'h', 'c': 'i', 'd': 'j', 'e': 'k', 'f': 'l'}, {'a': 'g', 'b': 'h', 'c': 'i', 'd': 'j', 'e': 'k', 'f': 'l'}]
>>> encoded = cbor2.dumps(bigl)
>>> encoded_shared = cbor2.dumps(bigl, value_sharing=True)
>>> len(encoded)
5002
>>> len(encoded_shared)
628
>>> cbor2.loads(encoded) == cbor2.loads(encoded_shared)
True
```

**Comment by felipeochoa** [comment]
Awesome! Might suggest adding a quick note to the docs with that, but maybe this issue is enough for those curious about this 😄
