### ISSUE TITLE
JSON Compatible flag is not used

### ISSUE THREAD

**Issue by Sekenre** [agronholm/cbor2#63]
There is a json_compatible flag mentioned in the documentation and in the encoder __slots__ attribute, but it appears to be unused.

Any objection to removing this, or is there an implementation somewhere?

**Comment by agronholm** [comment]
The idea behind this was that it could be used as a replacement for the other CBOR library which does not support any data types beyond those of JSON. The intended use case was replacing JSON on WAMP routers. I personally have no more interest in that, so I don't object to its removal.
