### ISSUE TITLE
Differing results on Python 2.7 and 3.7 when decoding canonical data

### ISSUE THREAD

**Issue by thephez** [agronholm/cbor2#70]
Stumbled across this today. When decoding the same bit of data, I'm getting results in different orders in Python2 vs 3. 

Python 3.7 is doing what I expect - I can encode the data and end up with the same result as the received, already encoded data. Python 2 provides a different result.

I created a repl to show each case. The code is identical - only the Python version is different (cbor2 v5.0.1). You can find them here:
Python 2.7 - https://repl.it/@thephez/cbor2-py27
Python 3.7 - https://repl.it/@thephez/cbor2-py37

**Comment by Sekenre** [comment]
Hi there,

This is actually caused by python 2.7 treating string literals as ASCII byte sequences.

If you add this to the top line of your file it works in 2.7:

```python
from __future__ import unicode_literals
```

**Comment by thephez** [comment]
Thanks! That did the trick.
