### ISSUE TITLE
`cbor2` cannot be installed when the system locale is C

### ISSUE THREAD

**Issue by a-rodin** [agronholm/cbor2#74]
The latest version 5.0.1 of `cbor2` package cannot be installed using `pip` from Python 3 when the system locale is `C`.

It means, in particular, that installation fails if `cbor2` is installed during building of a Docker image based on Ubuntu or Debian, unless the locale is explicitly configured before installing `cbor2`:

`Dockerfile`
```Dockerfile
FROM ubuntu:18.04
RUN apt-get update && apt-get install -y python3-pip
RUN pip3 install cbor2==5.0.1
```

```bash
$ docker build .
...
Step 3/3 : RUN pip3 install cbor2==5.0.1
 ---> Running in d25611af1b36
Collecting cbor2==5.0.1
  Downloading https://files.pythonhosted.org/packages/3e/2c/188d040bd4cf99012d0e847a3d95bf1ef1f783859b09eb9f736950af84f0/cbor2-5.0.1.tar.gz (72kB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-3fenoodl/cbor2/setup.py", line 52, in <module>
        **kwargs
      File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 128, in setup
        _install_setup_requires(attrs)
      File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 121, in _install_setup_requires
        dist.parse_config_files(ignore_option_errors=True)
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 491, in parse_config_files
        _Distribution.parse_config_files(self, filenames=filenames)
      File "/usr/lib/python3.6/distutils/dist.py", line 395, in parse_config_files
        parser.read(filename)
      File "/usr/lib/python3.6/configparser.py", line 697, in read
        self._read(fp, filename)
      File "/usr/lib/python3.6/configparser.py", line 1015, in _read
        for lineno, line in enumerate(fp, start=1):
      File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 149: ordinal not in range(128)
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-3fenoodl/cbor2/
The command '/bin/sh -c pip3 install cbor2==5.0.1' returned a non-zero code: 1
```

It is possible to configure the locale before running `pip`, for example by setting it to `en_US.UTF-8`, as suggested in https://github.com/dbohdan/remarshal/issues/24#issuecomment-599047829, but it would be nice if it was possible to install `cbor2` for any system locale.

**Comment by Sekenre** [comment]
Well after a quick bit of searching I found this bug in setuptools: https://github.com/pypa/setuptools/issues/1062 As a result of that, it appears that you need to update setuptools to at least v40.7

Here is the relevant changelog message: https://setuptools.readthedocs.io/en/latest/history.html#v40-7-0

Can you try that and let me know how you get on?

**Comment by Sekenre** [comment]
Side-note, if it works, I will update setup.py version requirements to make sure this doesn't trip up anyone else

**Comment by agronholm** [comment]
If it becomes a problem, you can just mangle my name in setup.cfg to not contain non-ASCII characters.

**Comment by a-rodin** [comment]
I tried to change `ubuntu:18.04` to `ubuntu:19.04` in the Dockerfile in my example and it worked. So I confirm that the is not present with newer versions of `setuptools`.

**Comment by Sekenre** [comment]
Ok thanks for confirming, I will include it in my next pr.
