### ISSUE TITLE
Error ingesting datetime with fractional seconds

### ISSUE THREAD

**Issue by BSipos-RKF** [agronholm/cbor2#8]
When the cbor2.load encounters a text-string-encoded date-time-tagged value which contains fractional seconds, the cbor2 library raises an `cbor2.decoder.CBORDecodeError` exception.

This occurs for string literals, for example '2017-07-22T00:24:07.236Z' and the library also fails loopback reading of library encoded date-times, for example:
`import cbor2
import datetime
import pytz
cbor2.loads(cbor2.dumps(datetime.datetime(2004, 5, 6, 7, 8, 9, tzinfo=pytz.utc)))
cbor2.loads(cbor2.dumps(datetime.datetime(2004, 5, 6, 7, 8, 9, 10, tzinfo=pytz.utc)))
`
results in exception:
`cbor2.decoder.CBORDecodeError: error decoding value at index 30: microsecond must be in 0..999999`

**Comment by agronholm** [comment]
I just tried your example code and it worked fine. Are you sure you have the latest release?

**Comment by BSipos-RKF** [comment]
I completely forgot to mention the version. I'm using cbor2-3.0.0.
I'm running this on Fedora 24 and had thought I was using a system-package-provided cbor2, but in fact I installed it with PIP and it's been at an old version for a while. I suppose this ticket can be closed as a known issue in older version then. Thanks.

**Comment by agronholm** [comment]
Seems like this was fixed by d3b6dbe.
