### ISSUE TITLE
Installation requires a compiler

### ISSUE THREAD

**Issue by virtuald** [agronholm/cbor2#86]
Currently, installing cbor2 fails if a compiler isn't installed. See https://github.com/agronholm/cbor2/blob/5e8491fe9449cbb4990d36e1fee2c93e9a10a499/setup.py#L24

There is a pure python fallback, but it seems the current setup.py will not actually use it most of the time. It would be great if the setup.py could check to see if compilation succeeds/could succeed, and fallback to pure python if the compilation fails. 

Alternatively publishing wheels for all common platforms would be great as well.

**Comment by agronholm** [comment]
I was able to install this without a compiler:
`pip3 install git+https://github.com/agronholm/cbor2.git`
The latest master has the `optional=True` flag set, but the latest release does not, hence the failure.
@Sekenre time to cut a patch release?

**Comment by Sekenre** [comment]
Done,
5.1.1 released with build improvements.
