### ISSUE TITLE
Segmentation fault at shutdown

### ISSUE THREAD

**Issue by chrysn** [agronholm/cbor2#89]
I've found a segmentation fault that I could reproduce on different machines, yet failed to pin down any further. As cbor2 is the only non-standard module involved I could not remove (started with four), I'm reporting this here. Please bear with me as some parts of this seem like no-ops, but I haven't found anything in this I could remove:

* Use a recent Debian sid (any state in the last few days should do, as systems I tested with ranged from not updated since end of May to freshly set up).
* `git clone https://github.com/agronholm/cbor2` (alternatively, wget and unpack [5.1.0](https://files.pythonhosted.org/packages/ee/80/bc617b7fd89855649e48eb8242e09535e1b75371ec8389313fa0f97e2a70/cbor2-5.1.0.tar.gz)).
* `python3 setup.py build`
* Create a `/tmp/test.py` containing

```python
import inspect
import cbor2
import csv
```

* `PYTHONPATH=build/lib.linux-x86_64-3.8 python3 /tmp/test.py`

On the first run, all is fine. On the second and subsequent runs, this segfaults. (No error message is printed, so unless your shell shows error codes, look at the return code).

Various observations I've made which didn't get me any further but might help you:

* This only happens at shutdown. When I found this, I was running through my test suite, which always passed, but segfaulted for some test cases to be run but not for others. The above is the minimal error case distilled from that.
* The first-run behavior stems from the `.pyc` files in the build directory. (Which is good because it's the only legitimate kind-of-reason I could come up with for this).
* The `-d -v -X faulthandler` arguments don't affect the segmentation fault, and may help in debugging.
* Running Python with `-X dev` or `-X tracemalloc` cause the error to disappear.
* `python -c "import inspect; ..."` does not cause the error.
* The last import can be replaced with other simple modules like argparse or socket. For the first import, I haven't found suitable substitutes.
* Running in gdb gives me the following traceback:

```backtrace
#0  unlink_chunk (p=p@entry=0xa45f60, av=0x7ffff7f75b80 <main_arena>) at malloc.c:1466
#1  0x00007ffff7e3fcc5 in _int_free (av=0x7ffff7f75b80 <main_arena>, p=0xa45f60, have_lock=<optimized out>) at malloc.c:4333
#2  0x00000000005ca653 in _Py_Dealloc (op=<optimized out>) at ../Objects/object.c:2215
#3  _Py_DECREF (filename=<synthetic pointer>, lineno=541, op=<optimized out>) at ../Include/object.h:478
#4  _Py_XDECREF (op=<optimized out>) at ../Include/object.h:541
#5  free_keys_object (keys=0xa3aec0) at ../Objects/dictobject.c:584
#6  0x00000000005caffc in dictkeys_decref (dk=0xa3aec0) at ../Objects/dictobject.c:324
#7  dict_dealloc (mp=0x7ffff76a5640) at ../Objects/dictobject.c:1998
#8  0x000000000069d953 in _Py_DECREF (filename=0x87d3e8 "../Objects/moduleobject.c", lineno=791, op=<optimized out>) at ../Include/object.h:478
#9  module_clear (m=<optimized out>) at ../Objects/moduleobject.c:791
#10 0x00000000004ec288 in delete_garbage (state=<optimized out>, state=<optimized out>, old=0x934820 <_PyRuntime+416>, collectable=0x7fffffffdcd0) at ../Modules/gcmodule.c:948
#11 collect.constprop.0 (generation=generation@entry=2, n_collected=n_collected@entry=0x0, n_uncollectable=n_uncollectable@entry=0x0, nofail=nofail@entry=1, 
    state=0x9347d8 <_PyRuntime+344>) at ../Modules/gcmodule.c:1123
#12 0x000000000066ab3b in _PyGC_CollectNoFail () at ../Modules/gcmodule.c:1866
#13 0x000000000067d580 in PyImport_Cleanup () at ../Python/import.c:542
#14 0x0000000000677ad0 in Py_FinalizeEx () at ../Python/pylifecycle.c:1240
#15 0x00000000006aea19 in Py_RunMain () at ../Modules/main.c:646
#16 0x00000000006aec89 in Py_BytesMain (argc=<optimized out>, argv=<optimized out>) at ../Modules/main.c:698
#17 0x00007ffff7ddfe0b in __libc_start_main (main=0x4eb6e0 <main>, argc=2, argv=0x7fffffffe018, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, 
    stack_end=0x7fffffffe008) at ../csu/libc-start.c:308
#18 0x00000000005f59da in _start () at ../Objects/obmalloc.c:1233
```
I didn't find any local that I could make sense of, especially with all the op being optimzied out.

I'll try to keep the particular setup around in case you can't repoduce it, but have ideas on which experiments to make with this.

**Comment by Sekenre** [comment]
This does not seem to happen with python 3.6, at least I can't get it to segfault?

**Comment by chrysn** [comment]
I'm glad this is happening that way reproducibly on two systems on 3.8; I have little hope to reproduce it *with this particular setup* on any other version.

(The underlying but may be easily around there too, but as the relevance of having other modules around in particular sequences already indicates, the symptom of actually segfaulting occurs rather rarely.)

**Comment by Sekenre** [comment]
@chrysn I am not able to reproduce this with 3.8 in a docker container. Is it possible that there are old build artifacts in your build folder that are causing a conflict?

**Comment by Sekenre** [comment]
Here is the dockerfile i used to test this. I was able to get it to segfault once, but can't reproduce it anymore.

```
FROM python:3.8

RUN mkdir /build
WORKDIR /build

RUN pip install --upgrade pip setuptools setuptools-scm \
    && git clone https://github.com/agronholm/cbor2 \
    && cd cbor2 && python3 setup.py build \
    && /bin/echo -e "import inspect\nimport cbor2\nimport csv\n" > /build/test_segf.py

WORKDIR /build/cbor2
ENV PYTHONPATH=build/lib.linux-x86_64-3.8

CMD ["python3", "/build/test_segf.py"]

```
