### ISSUE TITLE
Use OrderedDict to ensure re-encoded CBOR matches original CBOR

### ISSUE THREAD

**Issue by xachin** [agronholm/cbor2#9]
Currently if you decode a CBOR that contains a map of inner maps and then re-encode the result back to CBOR then the re-encoded CBOR does not match the original CBOR.

This is because Python's dictionary does not preserve the key order. If an OrderedDict is used to represent CBOR maps in Python then this issue can be resolved.

**Comment by agronholm** [comment]
Changeset 95d0a50b52c81f5f0e46fb3e5a1788a7ad9623f7 added canonical encoding as an option. Should work for you.
